---
title: "Comum R Functions"
output: 
  html_document:
    toc: true

---

# General

## Studio Clean Environment

```{r environment clear}
rm(list = ls())

```

## Clen console  crt+L



# ggplot com slider e medicao7

Need include text with values
```{r}
# library(manipulate)
# mu0 = 30
# myplot <- function(sigma, mua, n, alpha) {
# g = ggplot(data.frame(mu = c(27, 36)), aes(x = mu))
# g = g + stat_function(fun = dnorm, geom = "line", args = list(mean = mu0,
# sd = sigma/sqrt(n)), size = 2, col = "red")
# g = g + stat_function(fun = dnorm, geom = "line", args = list(mean = mua,
# sd = sigma/sqrt(n)), size = 2, col = "blue")
# xitc = mu0 + qnorm(1 - alpha) * sigma/sqrt(n)
# g = g + geom_vline(xintercept = xitc, size = 3)
# g
# }
# manipulate(myplot(sigma, mua, n, alpha), sigma = slider(1, 10, step = 1, initial = 4),
# mua = slider(30, 35, step = 1, initial = 32), n = slider(1, 50, step = 1,
# initial = 16), alpha = slider(0.01, 0.1, step = 0.01, initial = 0.05))
```





# Interative formula

```{r }
lambdavals <- seq(0.005, 0.1, by = 0.01)
nosim <- 1000
t <- 100
coverage <- sapply(lambdavals, function(lambda) {
lhats <- rpois(nosim, lambda = lambda * t)/t
ll <- lhats - qnorm(0.975) * sqrt(lhats/t)
ul <- lhats + qnorm(0.975) * sqrt(lhats/t)
mean(ll < lambda & ul > lambda)
})
```

