---
title: "Z6 Statistical Inference"
author: "Denis Lopes"
date: "28/10/2020"

output: 
  html_document:
    toc: true

---

# week 1 Probability
##   mobule 2 - video 02_03


```{r setup}
x <- c(-0.5, 0, 1, 1, 1.5)
y <- c(0, 0, 2, 0, 0)
plot(x, y, lwd = 3, frame = FALSE, type = "l")

```

Probability of 0.75 

```{r}
1.5 * 0.75/2
```

I can use 

```{r}
pbeta(0.75,2,1)
```

For many values

```{r}
pbeta(c(0.4, 0.5, 0.6), 2, 1)
```

Quantiles

```{r Quantiles qBeta}
qbeta(0.5625, 2, 1)
```


##   mobule 4 - video 04_01

Manipulate values

Problem in read values

```{r}
library(HistData)
library(manipulate)

myHist <- function(mu){
g <- ggplot(Galton, aes(x = child))
g <- g + geom_histogram(fill = "salmon",
binwidth=1, aes(y = ..density..), colour = "black")
g <- g + geom_density(size = 2)
g <- g + geom_vline(xintercept = mu, size = 2)
mse <- round(mean((Galton$child - mu)^2), 3)
g <- g + labs(title = paste('mu = ', mu, ' MSE = ', mse))
g
}

manipulate(myHist(mu), mu = slider(62, 74, step = 0.5))

```


